//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dinary
    {
        public int DinaryId { get; set; }
        public string mood { get; set; }
        public string weather { get; set; }
        public string write { get; set; }
        public Nullable<int> UserId { get; set; }
        public string picturetype { get; set; }
        public string FbName { get; set; }
        public byte[] picture { get; set; }
    
        public virtual User User { get; set; }
    }
}
